// <auto-generated />
using System;
using MachineStream.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MachineStream.Web.Migrations
{
    [DbContext(typeof(MachineEventsContext))]
    [Migration("20201116063905_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MachineStream.Web.Models.MachineEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Event")
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinRef")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MachineInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ref")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineInfoId");

                    b.ToTable("MachineEvents");
                });

            modelBuilder.Entity("MachineStream.Web.Models.MachineInfo", b =>
                {
                    b.Property<int>("MachineInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("MachineInfoId");

                    b.ToTable("MachineInfo");
                });

            modelBuilder.Entity("MachineStream.Web.Models.MachineEvent", b =>
                {
                    b.HasOne("MachineStream.Web.Models.MachineInfo", "MachineInfo")
                        .WithMany()
                        .HasForeignKey("MachineInfoId");

                    b.Navigation("MachineInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
